#!/bin/bash

echo "Welcome to NFV-Inspector monitoring server installation wizard :-)"


if [ -f ./config.json ]; then
   echo "A configuration already exists:"
   cat ./config.json
   echo "If you continue the installation it will overwrite above configuration. Are you sure to continue? (y/N): "
   read -r con
   if [ $con != 'y' ] || [ $con != 'Y' ]
      echo "Exiting installation"
      exit 0
   fi
fi
  
echo "Please choose wether you want to use ElasticSearch or InfluxDB as your time-series database backend: (1=ElasticSearch, 2=InfluxDB): "

read -r db

if [ $db -eq 1 ]
then
   echo "Please enter you ElasticSearch host: "
   read -r elasticsearch_host

   echo "Please enter your Elasticsearch port: "
   read -r elasticsearch_port

   echo "Please enter you Elasticsearch token (if exists): "
   read -r elasticsearch_token

   echo "Please enter your Elasticsearch username (if exists): "
   read -r elasticsearch_username

   echo "Please enter your Elasticsearch password (if exists): "
   read -r elasticsearch_password
  
   echo "Elasticsearch host: $elasticsearch_host \nElasticsearch port: $elasticsearch_port \nElasticsearch token: $elasticsearch_token\nElasticsearch username: $elasticsearch_username\nElasticsearch password: $elasticsearch_password\n"
   echo "Attempting to connect to Elasticsearch..."
fi
